[phases.setup]
# PHP core dan extension penting untuk aplikasi
nixPkgs = [
  "php82",
  "php82Extensions.mbstring",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql"
]

[phases.build]
cmds = []

[start]
cmd = "php -S 0.0.0.0:${PORT} -t ."
