[phases.setup]
nixPkgs = ['php82', 'php82Extensions.mbstring', 'php82Extensions.json']

[phases.install]
cmds = [
    'mkdir -p data',
    'chmod 777 data'
]

[start]
cmd = 'php -S 0.0.0.0:$PORT -t .'